include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Remind to use const constructors where possible
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # Allow printing to console
    avoid_print: false
