name: ground_scope
description: "A new Flutter project for aviation ground operations."
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  # UI & Navigation
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  persistent_bottom_nav_bar: ^6.2.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  cached_network_image: ^3.4.1
  flutter_animate: ^4.5.2

  # State Management & Logic
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^11.0.0
  equatable: ^2.0.8
  get_it: ^9.0.5

  # Backend & Infrastructure
  supabase_flutter: ^2.10.3
  firebase_core: ^4.2.1
  flutter_dotenv: ^6.0.0

  # Storage & Localization
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5
  easy_localization: ^3.0.8
  image_picker: ^1.2.1
  dio: ^5.9.2
  url_launcher: ^6.3.1
  firebase_messaging: ^16.4.1
  flutter_local_notifications: ^18.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21 # should match your android/app/build.gradle
  adaptive_icon_background: "#101922" # Required for Android "Adaptive Icons"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/svgs/
    - assets/lang/
    - .env

  # Typography configuration
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200

    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200